//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 443-Hw1
//  @ File Name : BasicKnight.java
//  @ Date : 08.04.2015
//  @ Author : Burak Goynuk
//
//

//package pkg443.hw1;

import java.awt.Graphics;
import javax.swing.Timer;


public class BasicKnight extends Knight {
    /*
    public void BasicKnight(){
    
    }
    */
    public BasicKnight( int iHitPoint, Timer iCoolDown, int iScore, double iXPos, double iYPos, double iSpeed, int iHealth, int iNormalAttack, int iSpecAttack, Simulation iSimulation ){
        hitPoint = iHitPoint;
        coolDown = iCoolDown;
        score = iScore;
        xPos = iXPos;
        yPos = iYPos;
        speed = iSpeed;
        health = iHealth;
        normalAttack = iNormalAttack;
        specAttack = iSpecAttack;
        simulation = iSimulation;
    }
    
    public void draw(Graphics g) {}
    public void doSpecAttack(){}
    public void doNormAttack(){}
}
