//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 443-Hw1
//  @ File Name : Grade2.java
//  @ Date : 08.04.2015
//  @ Author : Burak Goynuk
//
//

//package pkg443.hw1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;


public class Grade2 extends KnightDecorator {
	public Grade2(Knight component) {

            copyConsCommon( component );
	
	}
	
	public void draw(Graphics g) {

            drawCommon();
            
            
            Graphics2D g2d = (Graphics2D) g;
            //g2d.setRenderingHint (RenderingHints.KEY_ANTIALIASING,   RenderingHints.VALUE_ANTIALIAS_ON);

            int ovalSize = 10;
            g2d.setColor( Color.CYAN );
            g2d.fillOval((int) xPos + 15, (int) yPos - 25, ovalSize, ovalSize);
            //g2d.drawString("2", (int)xPos + 15, (int)yPos - 25);
            g2d.drawOval((int) xPos + 15, (int) yPos - 25, ovalSize, ovalSize);

            this.component.draw(g2d);   
	
	}
        
        @Override
        public void doNormAttack() 
        {
            this.component.doNormAttack();
            this.score = this.component.score;
            this.speed = this.component.speed;
        }

        @Override
        public void doSpecAttack() 
        {
            this.component.doSpecAttack();
            this.score = this.component.score;
            this.speed = this.component.speed;
        }
}
