//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 443-Hw1
//  @ File Name : KnightDecorator.java
//  @ Date : 08.04.2015
//  @ Author : Burak Goynuk
//
//

//package pkg443.hw1;

import java.awt.Graphics;


public class KnightDecorator extends Knight {
	public Knight component;
	public void draw(Graphics g) {
	}
        
        public void copyConsCommon( Knight component ){
            this.component = component;
            hitPoint = component.hitPoint;
            coolDown = component.coolDown;
            score = component.score;
            xPos = component.xPos;
            yPos = component.yPos;
            speed = component.speed;
            health = component.health;
            normalAttack = component.normalAttack;
            specAttack = component.specAttack;
            simulation = component.simulation;
            strategy = component.strategy;
            colorKnight = component.colorKnight;
            knightId = component.knightId;
            strategy = component.strategy;

        }
        public void drawCommon(){
            component.hitPoint = hitPoint;
            component.coolDown = coolDown;
            component.score = score;
            component.xPos = xPos;
            component.yPos = yPos;
            component.speed = speed;
            component.health = health;
            component.normalAttack = normalAttack;
            component.specAttack = specAttack;
            component.simulation = simulation;
            component.strategy = strategy;
            component.colorKnight = colorKnight;
            component.knightId = knightId;
       }
        
        
    @Override
    public void doSpecAttack() {
        /*
        this.component.doNormAttack();
        this.score = this.component.score;*/
    }

    @Override
    public void doNormAttack() {  
        /*
        this.component.doSpecAttack();
        this.score = this.component.score;*/
    }
}
