//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 443-Hw1
//  @ File Name : Priest.java
//  @ Date : 08.04.2015
//  @ Author : Burak Goynuk
//
//

//package pkg443.hw1;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.Timer;


public class Priest extends BasicKnight {
	public Priest( int iHitPoint, Timer iCoolDown, int iScore, double iXPos, double iYPos, double iSpeed, int iHealth, int iNormalAttack, int iSpecAttack, Simulation iSimulation ) {
           super( iHitPoint, iCoolDown, iScore, iXPos, iYPos, iSpeed, iHealth, iNormalAttack, iSpecAttack, iSimulation  );
	
           int strategyChoice = Simulation.random.nextInt(4);
            if ( strategyChoice == 0 )
            {
                strategy = new AttackClosest(this);
            }
            else if ( strategyChoice == 1 )
            {
                strategy = new AttackWeakest(this);
            }
            else if ( strategyChoice == 2 )
            {
                strategy = new RandomMove();
            }
            else if ( strategyChoice == 3 )
            {
                strategy = new AttackSlowest(this);
            }
            else{
            
            }
        
        
        }
	
	public void draw(Graphics g) {

            
            Graphics2D g2d = (Graphics2D) g;

            int rectSize = 30;

            g2d.setColor(colorKnight)                                            ;
            g2d.fillRect((int) xPos - 15, (int) yPos - 15, rectSize, rectSize);
            g2d.setColor(colorKnight)                                           ;
            g2d.drawRect((int) xPos - 15, (int) yPos - 15, rectSize, rectSize);

            //int fontSize                    =       15 ;

            Font defaultFont 		= 	g2d.getFont()                     		;  
            Font newFont     		= 	new Font("Times New Roman", Font.BOLD, 13 ) 	;
            g2d.setFont(newFont) 									;
            FontMetrics fm 			= 	g2d.getFontMetrics()                            ;
            g2d.setPaint( Color.WHITE) 							;
            String temp 			= 	Integer.toString( health ) 		;
            g2d.drawString( temp, (int) (xPos - 15 + ((rectSize - fm.stringWidth(temp))/2.0) ), (int) ( yPos - 15 + 13 + (rectSize - 13)/2.0 ) ) ; 
            g2d.setFont( defaultFont )  ;


            if ( attackType == 2 )
            {
                g2d.setColor(Color.GREEN);
                g2d.setStroke(new BasicStroke(2));
                g2d.drawOval( (int)xPos-45, (int)yPos-45, 100, 100);


            }
            else if ( attackType == 1 )
            {
                g2d.setColor(colorKnight);
                g2d.setStroke(new BasicStroke(3));
                if ( colorKnight == Color.RED )
                {
                    
                    g2d.drawLine( (int)xPos,(int)yPos, (int)xPos+50, (int)yPos-50);
                    //g2d.drawLine( (int)xPos,(int)yPos, (int)strategy.targetToAttack.xPos, (int)strategy.targetToAttack.yPos);
                }    

                else
                {
                    g2d.drawLine( (int)xPos,(int)yPos, (int)xPos-50, (int)yPos+50);
                    //g2d.drawLine( (int)xPos,(int)yPos, (int)strategy.targetToAttack.xPos, (int)strategy.targetToAttack.yPos);
                }    

            }
            attackType = 0;
        
            
        }
        
        @Override
        public void doSpecAttack(){
            
            Knight alies;
            double distance;
            if ( colorKnight == Color.RED )
            {
                for ( int i=0; i<simulation.kaurusList.size(); i++ )
                {
                    alies = simulation.kaurusList.get(i);
                    if ( alies != null  )
                    {    
                        distance = Strategy.findDistance(this, alies);
                        if ( distance < 100 )
                        {
                            attackType = 2;
                            alies.health += 75;
                            //;
                        }    
                    }    
                }    
            }
            else
            {
                for ( int i=0; i<simulation.elMoradList.size(); i++ )
                {
                    alies = simulation.elMoradList.get(i);
                    if ( alies != null )
                    {    
                        distance = Strategy.findDistance(this, alies);
                        if ( distance < 100 )
                        {
                            attackType = 2;
                            alies.health += 75;
                            //;
                        }    
                    }    
                } 
            
            
            
            }
        }
        
        
        @Override
        public void doNormAttack(){
            Knight target = this.strategy.targetToAttack;
            int resultAttack = 0;
            //System.out.println("Normal Attack Priest!");
            if ( target != null ){
                resultAttack = meleeAttack( target, 100 );
                //attackType = 1;
            }
            if ( resultAttack == 1 )
                attackType = 1;
        }

}
