//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 443-Hw1
//  @ File Name : Random.java
//  @ Date : 08.04.2015
//  @ Author : Burak Goynuk
//
//


//package pkg443.hw1;

public class RandomMove extends Strategy {
	
        Simulation simulation;
        public double scanRadius;
	public double randomTargetX = -1;     // Determine a point on the panel
	public double randomTargetY = -1;
        
        
	public void RandomMove(double scanRadius, Knight k) {
	
	}
	
	public void step(Knight k, double deltaTime) {
           
            
            
            double xMin = simulation.bottomLeftX;
            double yMin = simulation.topRightY;
            
            double xMax = simulation.topRightX;
            double yMax = simulation.bottomLeftY;
            
            if ( randomTargetX == -1 && randomTargetY == -1 )
            {
                int randomX = simulation.random.nextInt((int)xMax - (int)xMin + 1) + (int)xMin;
                int randomY = simulation.random.nextInt((int)yMax - (int)yMin + 1) + (int)yMin;
                randomTargetX = randomX;
                randomTargetY = randomY;
                Strategy.moveKnight(k, randomX, randomY, deltaTime);
            }
            else
            {
                Strategy.moveKnight(k, randomTargetX, randomTargetY, deltaTime);
            }
            
	}
        
        
        
        
}
