//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 443-Hw1
//  @ File Name : SoldierFactory.java
//  @ Date : 08.04.2015
//  @ Author : Burak Goynuk
//
//

//package pkg443.hw1;

import javax.swing.Timer;


public abstract class SoldierFactory {
	public Team team;
	public abstract Knight produce( int iHitPoint, Timer iCoolDown, int iScore, double iXPos, double iYPos, double iSpeed, int iHealth, int iNormalAttack, int iSpecAttack, Simulation iSimulation );
        
}
