//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : 443-Hw1
//  @ File Name : Team.java
//  @ Date : 08.04.2015
//  @ Author : Burak Goynuk
//
//

//package pkg443.hw1;

import java.awt.Color;


public class Team {
	public int score;
	public Color color;
	public SoldierFactory factories;
	public void Team() {
	
	}
}
